{% set name = "mmdet" %}
{% set version = "2.28.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/open-mmlab/mmdetection/archive/refs/tags/v{{ version }}.tar.gz
  sha256: eb4a20c4154d11cbca46708f61d6cee61914ec1e0e99fac8f43554c8f22b14f4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - pytorch
  run:
    - mmcv-full
    - numpy
    - py-opencv
    - pycocotools
    - python >=3.7
    - pytorch
    - scipy
    - six
    - terminaltables

test:
  imports:
    - mmdet
  requires:
    - pip
  commands:
    - pip check
    - python3 -c "import mmdet; print(mmdet.__version__)"

about:
  home: https://github.com/open-mmlab/mmdetection
  summary: OpenMMLab Detection Toolbox and Benchmark
  description: |
    MMDetection is an open source object detection toolbox based on PyTorch. It is a part of the OpenMMLab project.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://github.com/open-mmlab/mmdetection

extra:
  recipe-maintainers:
    - weiji14
    - apatsekin
