{% set name = "mmdet" %}
{% set version = "3.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/open-mmlab/mmdetection/archive/refs/tags/v{{ version }}.zip
  sha256: e13b75d58a55f881913776e3d0dced8cb20aa1294d66708f5a8c897c504d4d54

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - pytorch
    - setuptools
  run:
    - mmcv <2.2.0  # https://github.com/open-mmlab/mmdetection/issues/11668
    - numpy
    - py-opencv
    - pycocotools
    - python >={{ python_min }}
    - pytorch
    - scipy
    - shapely
    - six
    - terminaltables
    - tqdm

test:
  imports:
    - mmdet
  source_files:
    - configs
    - tests
  requires:
    - memory_profiler
    - parameterized
    - pip
    - psutil
    - pytest
    - python {{ python_min }}
    - scikit-image
    - scikit-learn
    - seaborn
  commands:
    # - pip check  # disabled because mmengine on conda-forge is mmengine-lite
    - ls -lh
    # Missing packages from conda-forge
    {% set tests_to_skip = "TestCorrupt" %}  # missing imagecorruptions dep
    {% set tests_to_skip = tests_to_skip + " or TestDetInferencer" %}  # missing panopticapi dep
    {% set tests_to_skip = tests_to_skip + " or TestInstaboost" %}  # missing instaboostfast dep
    {% set tests_to_skip = tests_to_skip + " or TestMOTChallengeMetric" %}  # missing trackeval dep
    # Incompatibilities since numpy 1.24 removed np.bool, np.float, np.long
    # https://numpy.org/doc/1.24/release/1.24.0-notes.html#expired-deprecations
    # https://numpy.org/doc/1.20/release/1.20.0-notes.html#using-the-aliases-of-builtin-types-like-np-int-is-deprecated
    {% set tests_to_skip = tests_to_skip + " or TestPackTrackInputs" %}  # np.bool
    {% set tests_to_skip = tests_to_skip + " or TestYouTubeVISMetric" %}  # np.float
    {% set tests_to_skip = tests_to_skip + " or test_rotate" %}  # np.float
    {% set tests_to_skip = tests_to_skip + " or test_paa_head_loss" %}  # np.long
    - $PYTHON -m pytest --color=yes --verbose -rxXs -k "not ({{ tests_to_skip }})" tests/
    - python -c "import mmdet; print(mmdet.__version__)"

about:
  home: https://github.com/open-mmlab/mmdetection
  summary: OpenMMLab Detection Toolbox and Benchmark
  description: |
    MMDetection is an open source object detection toolbox based on PyTorch. It is a part of the OpenMMLab project.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://github.com/open-mmlab/mmdetection

extra:
  recipe-maintainers:
    - weiji14
    - apatsekin
