{% set name = "mmdet" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/open-mmlab/mmdetection/archive/refs/tags/v{{ version }}.zip
  sha256: ec1e3917f1b93c0b9f4c5b8846809d47a8616975fbacbf111c3f5048c28a4d0e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - pytorch
  run:
    - mmcv
    - numpy
    - py-opencv
    - pycocotools
    - python >=3.7
    - pytorch
    - scipy
    - shapely
    - six
    - terminaltables

test:
  imports:
    - mmdet
  requires:
    - pip
  commands:
    - pip check
    - python -c "import mmdet; print(mmdet.__version__)"

about:
  home: https://github.com/open-mmlab/mmdetection
  summary: OpenMMLab Detection Toolbox and Benchmark
  description: |
    MMDetection is an open source object detection toolbox based on PyTorch. It is a part of the OpenMMLab project.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://github.com/open-mmlab/mmdetection

extra:
  recipe-maintainers:
    - weiji14
    - apatsekin
